SLEEP_LED_ENABLE = no

OLED_ENABLE = yes
OLED_DRIVER_ENABLE = yes
LTO_ENABLE = yes  # Makes hex file smaller
WPM_ENABLE = yes

BACKLIGHT_ENABLE = no
AUDIO_ENABLE = no
RGBLIGHT_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
